import GoogleAnalytics from "@/components/GoogleAnalytics";

import "../globals.css";

<<<<<<< HEAD
=======


>>>>>>> 6a35b301af519cf231a5a0f66c993cda05f33101
export const metadata = {
  title: "Deaa Aldin Alawad",
  description: "Generated by Deaa Aldin Alawad",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta content="width=device-width,inital-scale=1" name="viewport" />
        <link rel="icon" href="/dea.ico" />
        <GoogleAnalytics GA_MEASUREMENT_ID="G-FLSVT5K5VH" />
      </head>
      <body>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-WHDNVZL4"
            height="0"
            width="0"
            style={{ visibility: "hidden", display: "none" }}
          ></iframe>
        </noscript>
        {children}
<<<<<<< HEAD
=======
       
>>>>>>> 6a35b301af519cf231a5a0f66c993cda05f33101
      </body>
    </html>
  );
}
